# Generated by Django 3.1.6 on 2021-07-05 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='dateposted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
